require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WitnessesController do

  # This should return the minimal set of attributes required to create a valid
  # Witness. As you add validations to Witness, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WitnessesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all witnesses as @witnesses" do
      witness = Witness.create! valid_attributes
      get :index, {}, valid_session
      assigns(:witnesses).should eq([witness])
    end
  end

  describe "GET show" do
    it "assigns the requested witness as @witness" do
      witness = Witness.create! valid_attributes
      get :show, {:id => witness.to_param}, valid_session
      assigns(:witness).should eq(witness)
    end
  end

  describe "GET new" do
    it "assigns a new witness as @witness" do
      get :new, {}, valid_session
      assigns(:witness).should be_a_new(Witness)
    end
  end

  describe "GET edit" do
    it "assigns the requested witness as @witness" do
      witness = Witness.create! valid_attributes
      get :edit, {:id => witness.to_param}, valid_session
      assigns(:witness).should eq(witness)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Witness" do
        expect {
          post :create, {:witness => valid_attributes}, valid_session
        }.to change(Witness, :count).by(1)
      end

      it "assigns a newly created witness as @witness" do
        post :create, {:witness => valid_attributes}, valid_session
        assigns(:witness).should be_a(Witness)
        assigns(:witness).should be_persisted
      end

      it "redirects to the created witness" do
        post :create, {:witness => valid_attributes}, valid_session
        response.should redirect_to(Witness.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved witness as @witness" do
        # Trigger the behavior that occurs when invalid params are submitted
        Witness.any_instance.stub(:save).and_return(false)
        post :create, {:witness => {}}, valid_session
        assigns(:witness).should be_a_new(Witness)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Witness.any_instance.stub(:save).and_return(false)
        post :create, {:witness => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested witness" do
        witness = Witness.create! valid_attributes
        # Assuming there are no other witnesses in the database, this
        # specifies that the Witness created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Witness.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => witness.to_param, :witness => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested witness as @witness" do
        witness = Witness.create! valid_attributes
        put :update, {:id => witness.to_param, :witness => valid_attributes}, valid_session
        assigns(:witness).should eq(witness)
      end

      it "redirects to the witness" do
        witness = Witness.create! valid_attributes
        put :update, {:id => witness.to_param, :witness => valid_attributes}, valid_session
        response.should redirect_to(witness)
      end
    end

    describe "with invalid params" do
      it "assigns the witness as @witness" do
        witness = Witness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Witness.any_instance.stub(:save).and_return(false)
        put :update, {:id => witness.to_param, :witness => {}}, valid_session
        assigns(:witness).should eq(witness)
      end

      it "re-renders the 'edit' template" do
        witness = Witness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Witness.any_instance.stub(:save).and_return(false)
        put :update, {:id => witness.to_param, :witness => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested witness" do
      witness = Witness.create! valid_attributes
      expect {
        delete :destroy, {:id => witness.to_param}, valid_session
      }.to change(Witness, :count).by(-1)
    end

    it "redirects to the witnesses list" do
      witness = Witness.create! valid_attributes
      delete :destroy, {:id => witness.to_param}, valid_session
      response.should redirect_to(witnesses_url)
    end
  end

end
